Corbin/Corbin/Controllers/MyProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Corbin.Models;
using Microsoft.AspNet.Identity;

namespace Corbin.Controllers
{
    
    public class MyProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MyProjects
        public ActionResult Index()
        {
            var MyProjects = db.MyProjects.Include(p => p.User);
            List<ProjectViewModel> ProjectVMs = AutoMapper.Mapper.Map<List<MyProject>, List<ProjectViewModel>>(MyProjects.ToList());
            return View(ProjectVMs.ToList());
        }

        // GET: MyProjects/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyProject proj = db.MyProjects.Find(id);
            ProjectDetailsViewModel ProjectVM = AutoMapper.Mapper.Map<MyProject, ProjectDetailsViewModel>(proj);
            ProjectVM.Images = db.ProjectImages.Where(u => u.ProjectId == proj.Id).ToList();

            if (proj == null)
            {
                return HttpNotFound();
            }
            return View(ProjectVM);
        }

        // GET: MyProjects/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: MyProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Title,Description,ImageFile")] ProjectCreateViewModel model)
        {
            // Initialization.  
            string fileContent = string.Empty;
            string fileContentType = string.Empty;

            try
            {

                if (ModelState.IsValid)
                {
                    MyProject proj = AutoMapper.Mapper.Map<ProjectCreateViewModel, MyProject>(model);
                    proj.EntryDate = DateTime.Now;
                    proj.LastUpdated = DateTime.Now;
                    proj.ApplicationUserId = User.Identity.GetUserId();
                    db.MyProjects.Add(proj);
                    db.SaveChanges();
                    int test = proj.Id;
                    //return RedirectToAction("Index");
                



                    ProjectImage projImage = new ProjectImage();
                    // Converting to bytes.  
                    byte[] uploadedFile = new byte[model.ImageFile.InputStream.Length];
                    model.ImageFile.InputStream.Read(uploadedFile, 0, uploadedFile.Length);


                    // Initialization.  
                    fileContent = Convert.ToBase64String(uploadedFile);
                    fileContentType = model.ImageFile.ContentType;

                    projImage.ImageStream = uploadedFile;
                    projImage.IsMainImage = true;
                    projImage.ProjectId = proj.Id;
                    projImage.ContentType = fileContentType;
                    projImage.Name = model.ImageFile.FileName;

                    db.ProjectImages.Add(projImage);
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                // Info  
                Console.Write(ex);
            }
            
            //ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", projVM.ApplicationUserId);
            return View(model);
        }

        // GET: MyProjects/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyProject proj = db.MyProjects.Find(id);
            ProjectEditViewModel ProjectVM = AutoMapper.Mapper.Map<MyProject, ProjectEditViewModel>(proj);
            ProjectVM.Images = db.ProjectImages.Where(u => u.ProjectId == proj.Id).ToList(); if (proj == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", proj.ApplicationUserId);
            return View(ProjectVM);
        }

        // POST: MyProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,EntryDate,LastUpdated,ApplicationUserId")] MyProject proj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proj).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Email", proj.ApplicationUserId);
            return View(proj);
        }

        // GET: MyProjects/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyProject proj = db.MyProjects.Find(id);
            if (proj == null)
            {
                return HttpNotFound();
            }
            return View(proj);
        }

        // POST: MyProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            MyProject proj = db.MyProjects.Find(id);
            db.MyProjects.Remove(proj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public JsonResult GetAll()
        {
            var MyProjects = db.MyProjects.Include(p => p.User);
            List<ProjectViewModel> ProjectVMs = AutoMapper.Mapper.Map<List<MyProject>, List<ProjectViewModel>>(MyProjects.ToList());
            return Json(ProjectVMs.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

Corbin/Corbin/Controllers/RegisterEmailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Corbin.Models;

namespace Corbin.Controllers
{
    public class RegisterEmailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RegisterEmails
        [Authorize]
        public ActionResult Index()
        {
            return View(db.RegisterEmails.ToList());
        }

        // GET: RegisterEmails/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterEmail registerEmail = db.RegisterEmails.Find(id);
            if (registerEmail == null)
            {
                return HttpNotFound();
            }
            return View(registerEmail);
        }

        // GET: RegisterEmails/Register
        public ActionResult Register()
        {
            return View();
        }

        // POST: RegisterEmails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "Email")] RegisterEmail registerEmail)
        {
            if (db.RegisterEmails.Any(o => o.Email == registerEmail.Email))
            {
                AddErrors("Email is already registered");
                return View(registerEmail);
            }

            if (ModelState.IsValid)
            {
                db.RegisterEmails.Add(registerEmail);
                try
                {
                    db.SaveChanges();
                }
                catch
                {
                    AddErrors("There was an error registering the email. If the problem persists please contact the administrator.");
                    return View(registerEmail);
                }
                return RedirectToAction("Index");
            }

            return View(registerEmail);
        }

        private void AddErrors(String result)
        {
            ModelState.AddModelError("", result);           
        }

        // GET: RegisterEmails/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterEmail registerEmail = db.RegisterEmails.Find(id);
            if (registerEmail == null)
            {
                return HttpNotFound();
            }
            return View(registerEmail);
        }

        // POST: RegisterEmails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Email")] RegisterEmail registerEmail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registerEmail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(registerEmail);
        }

        // GET: RegisterEmails/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegisterEmail registerEmail = db.RegisterEmails.Find(id);
            if (registerEmail == null)
            {
                return HttpNotFound();
            }
            return View(registerEmail);
        }

        // POST: RegisterEmails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            RegisterEmail registerEmail = db.RegisterEmails.Find(id);
            db.RegisterEmails.Remove(registerEmail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Corbin/Corbin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
          crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datatables")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
            crossorigin="anonymous"></script>
</head>
<body>
    @*@using Microsoft.AspNet.Identity*@
    <div class="wrapper">
        <div id="sidebar">
            <div class="sidebar-header">
                <div class="row">
                    <div class="col-10" style="margin:0; padding:0;">
                        <h3>Main Menu</h3>
                    </div>
                    <div class="col" style="margin:0; padding:0;">
                        <div id="sidebarCollapse" class="navbar-btn">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>
                </div>
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fas fa-home"></i>
                        <span class="toggle show">Home</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "MyProjects")">
                        <i class="fas fa-briefcase"></i>
                        <span class="toggle show">Projects</span>
                    </a>
                </li>

                @if (!User.Identity.IsAuthenticated)
                {
                    <li>
                        <a href="@Url.Action("Login", "Account")">
                            <i class="fas fa-copy"></i>
                            <span class="toggle show">Admin Login</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Register", "RegisterEmails")">
                            <i class="fas fa-address-card"></i>
                            <span class="toggle show">Register Email</span>
                        </a>
                    </li>
                }
                else
                {
                    @*<li>
                            <a href="@Url.Action("Index", "MyProjects")">
                                <i class="fas fa-copy"></i>
                                <span class="toggle show">My Projects</span>
                            </a>
                        </li>*@
                    <li>
                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:document.getElementById('logoutForm').submit()">
                                <i class="fas fa-address-card"></i>
                                <span class="toggle show">Logoff</span>
                            </a>
                        }
                    </li>

                }



            </ul>
        </div>
        @RenderBody()
        <footer id="footer">
            <div id="footerText">&copy; @DateTime.Now.Year - Corbin Adkins</div>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @RenderSection("scripts", required: false)
</body>
</html>